version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3000:3001"
    env_file:
      - server/.env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"